In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.5.1+cu121


## Introduction to tensor

### Creating tensor

In [2]:
# scalar
scalar= torch.tensor(7)
scalar

tensor(7)

In [3]:
scalar.ndim

0

In [4]:
#get tensor back as python int
scalar.item()


7

In [5]:
#vector
vector= torch.tensor([7,7])
vector

tensor([7, 7])

In [6]:
vector.ndim

1

In [7]:
vector.shape

torch.Size([2])

In [8]:
# Matrix
MATRIX= torch.tensor([[7,8],[9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [9]:
MATRIX.ndim

2

In [10]:
MATRIX[0]

tensor([7, 8])

In [11]:
MATRIX.shape

torch.Size([2, 2])

In [12]:
# Tensor
TENSOR= torch.tensor([[[1,2,3],
                      [2,6,9],
                      [2,4,6]]])
TENSOR

tensor([[[1, 2, 3],
         [2, 6, 9],
         [2, 4, 6]]])

In [13]:
TENSOR.ndim

3

In [14]:
TENSOR.shape

torch.Size([1, 3, 3])

In [15]:
TENSOR[0]

tensor([[1, 2, 3],
        [2, 6, 9],
        [2, 4, 6]])

In [16]:
TENSOR= torch.tensor([[[[1,2,4]]]])
TENSOR.shape

torch.Size([1, 1, 1, 3])

In [17]:
TENSOR.ndim

4

In [18]:
TENSOR[0]

tensor([[[1, 2, 4]]])

### Random Tensors

Random tensor are important because the way many neural network learn is that they start with tensors full of random numbers to better represent data.

In [19]:
# Create a random tensor of shape (3,4)
random_tensor= torch.rand(3,4)
random_tensor

tensor([[0.8971, 0.1497, 0.2167, 0.8130],
        [0.2969, 0.8582, 0.7670, 0.4246],
        [0.1399, 0.7785, 0.1575, 0.6871]])

In [20]:
random_tensor.ndim

2

In [21]:
# create a random tensor similar shape to image tensor
random_image_size_tensor= torch.rand(size=(224,224,3)) #height width and RGB
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [22]:
torch.rand(size=(3,3))

tensor([[0.2091, 0.9452, 0.4066],
        [0.0875, 0.3898, 0.2244],
        [0.2219, 0.9880, 0.5387]])

## Zeros and Ones

In [23]:
# create a tensor of all zeros
zeros= torch.zeros(3,4)
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [24]:
ones= torch.ones(3,4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [25]:
ones.dtype

torch.float32

In [26]:
random_tensor.dtype

torch.float32

# creating a range of tensor and tensors-like

In [27]:
# use torch.range()
one_to_ten=torch.arange(1,11,1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [28]:
# Creating tensors like
ten_zeros= torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

# Tensor Datatypes

In [29]:
# float 32 tensor
float_32_tensor= torch.tensor([3.0,6.0,9.0],
                              dtype=None, #what datatype is of tensor
                              device=None, #which device you want as cuda or cpu
                              requires_grad= False)#whether or nor to track gradient
float_32_tensor


tensor([3., 6., 9.])

In [30]:
float_32_tensor.dtype

torch.float32

In [31]:
float_16_tensor= float_32_tensor.type(torch.float16)
float_16_tensor


tensor([3., 6., 9.], dtype=torch.float16)

In [32]:
float_16_tensor* float_32_tensor

tensor([ 9., 36., 81.])

In [33]:
float_16_tensor.dtype

torch.float16

In [34]:
int_32_tensor= torch.tensor([3,6,9], dtype= torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [35]:
float_32_tensor*int_32_tensor

tensor([ 9., 36., 81.])

### getting information from tensors

1. Tensor not right datatype
2. Tensor not right shape
3. Tensor not on right device

In [36]:
# create a tensor

some_tensor= torch.rand(3,4)
print(some_tensor)
print(some_tensor.dtype)
print(some_tensor.shape)


tensor([[0.5905, 0.0598, 0.3123, 0.4154],
        [0.7712, 0.8273, 0.4252, 0.3209],
        [0.7158, 0.4496, 0.2337, 0.3564]])
torch.float32
torch.Size([3, 4])


In [37]:
some_tensor.device

device(type='cpu')

### manipulating tensors (tensor operations)

tensor operation include:
* Addition
* Subtraction
* Multiplication
* Division
* Matrix Multiplication

In [38]:
# Create a tensor

tensor= torch.tensor([1,2,3])
tensor+10

tensor([11, 12, 13])

In [39]:
# Multiply tensor by 10
tensor=tensor*10
tensor


tensor([10, 20, 30])

In [40]:
#subtraction
tensor-100

tensor([-90, -80, -70])

In [41]:
# try out python in-built function
torch.mul(tensor,10)

tensor([100, 200, 300])

### matrix multiplication

two ways of multiplication in NN and deeplearning
1. element-wise
2. matrix

there are 2 main rules for matrix multiplication:
1. the ** inner dimensions** must match:
* `(3,2) @ (3,2)` won't work
* `(2,3) @ (3,2)` will work
* `(3,2) @ (2,3) ` will work

2. The resulting matrix has shape of ** outer dimension **:
* `(2,3) @ (3,2)` ->(2,2)
* `(3,2) @ (2,3) ` ->(3,3)



In [42]:
a=torch.matmul(torch.rand([3,2]) ,torch.rand([2,3])) #inner dimensons match
print(a.shape)
print(a)

torch.Size([3, 3])
tensor([[0.9127, 0.4947, 0.3675],
        [1.4071, 0.7493, 1.1004],
        [1.0432, 0.5603, 0.6244]])


In [43]:
tensor=tensor/10

In [44]:
tensor

tensor([1., 2., 3.])

In [45]:
torch.matmul(tensor,tensor)

tensor(14.)

### One of the most common error in Deep learning is shape error

In [46]:
# shapes for matrix multiplication

tensor_A= torch.tensor([[1,2],
                       [3,4],
                       [5,6]])
tensor_B= torch.tensor([[7,8],
                        [9,10],
                        [11,12]])

torch.matmul(tensor_A,tensor_B) # we can also write torch.mm(tensor_A,tensor_B)
#here dimentiona should be made as per rule as down done

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [47]:
tensor_A.shape,tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

to fix our tensor shape issues, we can manuplate the shape of one of our tensor using a transpose.
A transpose switches the axes or dimension of a given tensor.

In [48]:
B=tensor_B.T, tensor_B.T.shape
B

(tensor([[ 7,  9, 11],
         [ 8, 10, 12]]),
 torch.Size([2, 3]))

In [49]:
# the matrix multiplication operation works with tensor_B is transposed

torch.matmul(tensor_A, tensor_B.T), torch.matmul(tensor_A, tensor_B.T).shape

(tensor([[ 23,  29,  35],
         [ 53,  67,  81],
         [ 83, 105, 127]]),
 torch.Size([3, 3]))

## Finding the min, max, mean, sum, ect(tensor aggeration)

In [50]:
# create a tensor

x= torch.arange(1,100,10)
x

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [51]:
# find min
torch.min(x), x.min()

(tensor(1), tensor(1))

In [52]:
# find max
torch.max(x), x.max()

(tensor(91), tensor(91))

In [53]:
# find mean
torch.mean (x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(46.), tensor(46.))

In [54]:
# find sum

torch.sum(x), x.sum()

(tensor(460), tensor(460))

## finding the position of min and max


In [55]:
x

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [56]:
# find the postion in tensor that have minimum value and the index with argmin() function which returns index
x.argmin()

tensor(0)

In [57]:
# find max positon with argmax()
x.argmax()

tensor(9)

## Reshaping, stacking, squeezing and unsequeezing tensors.

* Reshaping- reshape an input tensor to a defined shape
* view- return view of an input tensor of a certain shape but keep the same memory as the original tensor
* Stacking- combine multiple tensors on top of each other (vstack) or side by side (hstack)
* Squeeze- remove all `1` dimenion to a target tensor
* Unsqueeze- add a dimension to a target tensor
* permute- Return a view of input with dimensions permmuted (swapped) in a ceratin way.

In [58]:
# lets create a tensor
import torch

x= torch.arange(1.,10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [59]:
# add an extra dimension
x_reshaped= x.reshape(1,9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [60]:
# change the view

z= x.view(1,9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [61]:
# changing z changes x (becuse a view of a tensor shares the same memory as the original input)
z[:,0]=5
z,x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [62]:
# stack tensors on top of each other
x_stacked= torch.stack([x,x,x,x], dim=1)
x_stacked

tensor([[5., 5., 5., 5.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.],
        [8., 8., 8., 8.],
        [9., 9., 9., 9.]])

In [63]:
# squeez and unsqueez the tensor now
# torch.squeeze() removes all single dimentions from a target tensor
a= torch.zeros(2,1,2,1,2)
a.size(),a

(torch.Size([2, 1, 2, 1, 2]),
 tensor([[[[[0., 0.]],
 
           [[0., 0.]]]],
 
 
 
         [[[[0., 0.]],
 
           [[0., 0.]]]]]))

In [64]:
b= torch.squeeze(a)
b.size(),b

(torch.Size([2, 2, 2]),
 tensor([[[0., 0.],
          [0., 0.]],
 
         [[0., 0.],
          [0., 0.]]]))

In [65]:
b= torch.squeeze(a,0)
b.size(),b

(torch.Size([2, 1, 2, 1, 2]),
 tensor([[[[[0., 0.]],
 
           [[0., 0.]]]],
 
 
 
         [[[[0., 0.]],
 
           [[0., 0.]]]]]))

In [66]:
b= torch.squeeze(a,1)
b.size(),b

(torch.Size([2, 2, 1, 2]),
 tensor([[[[0., 0.]],
 
          [[0., 0.]]],
 
 
         [[[0., 0.]],
 
          [[0., 0.]]]]))

In [67]:
x_reshaped.shape

torch.Size([1, 9])

In [68]:
x_reshaped.squeeze().shape

torch.Size([9])

In [69]:
# torch.unsqueeze() adds a single to a target tensor at a specific dim
x_unsequeezed= x_reshaped.unsqueeze(dim=1)
x_unsequeezed, x_unsequeezed.shape

(tensor([[[5., 2., 3., 4., 5., 6., 7., 8., 9.]]]), torch.Size([1, 1, 9]))

In [70]:
# torch.permute - rearranges the dimensions of a target tensor in a specificed order
x_original= torch.rand(size=(224,224,3))  #[height, width, RGB]

# permute the original tensor to rearrange the axis or dim order
x_permuted= x_original.permute(2,0,1) #shifts axis 0->1 , 1->2, 2->0
print(f'pervious shape: {x_original.shape}')
print(f'new shape: {x_permuted.shape}') #[RGB, height, width]


pervious shape: torch.Size([224, 224, 3])
new shape: torch.Size([3, 224, 224])


In [71]:
x_original[0,0,0]

tensor(0.4944)

 ## Indexing( selecting data from tensor)

 Indexing with pytorch is similar to indexing with Numpy

In [72]:
# creat a tensor
import torch
x= torch.arange(1,10).reshape(1,3,3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [73]:
#lets index on our new tensor
x[0]
x[0][1]
x[0][1][2]

tensor(6)

In [74]:
# we can also use ":" to select "all" of the target dimension
x[:,0]
x[:,:,2]
x[:,1,2]
x[0,0,:]

tensor([1, 2, 3])

In [75]:
x[0,2,2]
x[:,2,2]
x[:,:,2]

tensor([[3, 6, 9]])

In [76]:
x

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

## pytorch tensor and numpy

numpy is a popular scientific python numerical computing library

And because of this, pytorch has functionality to interact with it.

* Data in numpy , want in Pytorch tensor -> `torch.from_numpy(ndarray)`
* Pytorch tensor -> Numpy -> `torch.Tensor.numpy()`

In [77]:
# Numpy array to tensor
import torch
import numpy as np

array= np.arange(1.0,8.0)
tensor= torch.from_numpy(array).type(torch.float32) # warning when converting from numpy, pytorch reflect numpy default datatype float64 unless specified
array,tensor, tensor.dtype

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.]),
 torch.float32)

In [78]:
#change the value of arrray what will do this to tensor
array= array+1

array,tensor
array.dtype

dtype('float64')

In [79]:
tensor.dtype

torch.float32

In [80]:
torch.arange(1.0,8.0).dtype

torch.float32

In [81]:
# tensor to Numpy array

tensor= torch.ones(7)
numpy_tensor= tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [82]:
# change the tensor, what hapens to numpy_tensor ?
tensor= tensor+1
tensor,tensor.dtype, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 torch.float32,
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

### Reproducbility (trying to take random out of random)

In short how a neural network learns:

`start with random numhers -> tensor operations -> update random numbers to try and make them better representation of the date -> again -> again ->again...`

To reduce the randomness in NN and pytorch comes the concept of a **random seed**.
Essentially what the random seed does is "flovour" the randomness


In [83]:
import torch

#create 2 random tensors
random_tensor_A= torch.rand(3,4)
random_tensor_B= torch.rand(3,4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[5.3896e-01, 5.4497e-01, 9.5943e-01, 7.2255e-01],
        [5.7548e-01, 6.1419e-01, 8.6638e-01, 2.4116e-01],
        [3.0697e-01, 6.0307e-01, 8.9872e-04, 2.4603e-01]])
tensor([[0.4761, 0.5812, 0.5846, 0.9559],
        [0.2478, 0.0815, 0.5249, 0.0233],
        [0.2881, 0.1934, 0.7188, 0.1391]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [84]:
# lets make some radnom but reproducible tensors
import torch

#set the random seed
RANDOM_SEED= 42
torch.manual_seed(RANDOM_SEED)
random_tensor_C= torch.rand(3,4)

torch.manual_seed(RANDOM_SEED)
random_tensor_D= torch.rand(3,4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C== random_tensor_D)



tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


## Running tensors and Pytorch object on the GPUs ( and making faster computation)

GPUs = faster  computation on numbers

### 1. Getting a GPU

1. Eaisest way to get a GPU is by using gooble colab
2. use your own GPU for faster computing time as it take a setup and money for purchasing
3. use cloud computing

## 2. Checking for GPU access with pytorch

In [85]:
# check for GPU access with Pytorch
import torch
torch.cuda.is_available()

False

In [86]:
device= 'cuda' if torch.cuda.is_available() else 'cpu'
device

'cpu'

In [87]:
# count number of devices

torch.cuda.device_count()

0

Manupulating tensor (tensor operation)

In [88]:
# Create a tensor
tensor= torch.tensor([1,2,3])
print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [89]:
# move tensor to gpu(if avialable)
tensor_on_gpu= tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3])

### 4. moving tensor back to cpu

In [90]:
tensor_on_gpu.numpy()

array([1, 2, 3])

In [91]:
tensor= torch.rand(7,7)
tensor.shape,tensor


(torch.Size([7, 7]),
 tensor([[0.8694, 0.5677, 0.7411, 0.4294, 0.8854, 0.5739, 0.2666],
         [0.6274, 0.2696, 0.4414, 0.2969, 0.8317, 0.1053, 0.2695],
         [0.3588, 0.1994, 0.5472, 0.0062, 0.9516, 0.0753, 0.8860],
         [0.5832, 0.3376, 0.8090, 0.5779, 0.9040, 0.5547, 0.3423],
         [0.6343, 0.3644, 0.7104, 0.9464, 0.7890, 0.2814, 0.7886],
         [0.5895, 0.7539, 0.1952, 0.0050, 0.3068, 0.1165, 0.9103],
         [0.6440, 0.7071, 0.6581, 0.4913, 0.8913, 0.1447, 0.5315]]))

In [92]:
y= torch.rand(1,7)
z= torch.matmul(tensor,y.T)
z,z.shape

(tensor([[1.9625],
         [1.0950],
         [0.9967],
         [1.8910],
         [1.9205],
         [1.0674],
         [1.6949]]),
 torch.Size([7, 1]))

In [93]:
torch.manual_seed(0)
x= torch.rand(7,7)
y= torch.rand(1,7)
z= torch.matmul(x,y.T)
z, z.shape

(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]),
 torch.Size([7, 1]))